# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
