# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0003_auto_20160512_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
