# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0006_auto_20160512_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=b'author', max_length=100),
        ),
    ]
