# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0007_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contenturl',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default=b'Enjoy Reading!', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageurl',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=b'book', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='attime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=b'category', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default=b'new comment', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=b'new user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=b'123456', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='regtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
