# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0010_auto_20160512_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contenturl',
            field=models.CharField(default=b'#', max_length=200),
        ),
    ]
