# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0011_auto_20160512_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='OnlineLibraryApp.User'),
        ),
    ]
