# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0012_auto_20160512_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineLibraryApp.User'),
        ),
    ]
