# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0013_auto_20160512_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=b'author', max_length=100),
        ),
    ]
