# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0016_auto_20160512_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=b'13900000000', max_length=50),
        ),
    ]
