# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0017_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='largeimageurl',
            field=models.CharField(default=b'http://www.readanybook.com/covers/105799/big', max_length=200),
        ),
    ]
