# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0018_book_largeimageurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
    ]
