# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0019_auto_20160513_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imageurl',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
