# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibraryApp', '0024_suibian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiBian',
        ),
    ]
